apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: step-output

on:
  push:
    branches:
      - "**"
      
jobs:
  my-job-1:
    steps:
      - name: My first step
        uses: docker://alpine:3.18
        id: step1
        run: echo "hello there" > "$CLOUDBEES_OUTPUTS/greeting"
      - name: My second step
        uses: docker://alpine:3.18
        id: step2
        run: echo "from the hive ${{steps.step1.outputs.greeting}}"
